name: Release

# 触发器
on:
    workflow_dispatch:
        inputs:
            root_sol:
                description: 'Release Title'
                required: true
                default: 'SmsForwarder'
            version:
                description: 'Version'
                required: true
                default: '0.1.0'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # 检出代码
            - uses: actions/checkout@v4
            # 设置jdk环境为11
            - name: set up JDK 11
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '11'
                  java-package: jdk
            # 打包release
            - name: Build with Gradle
              run: bash ./gradlew assembleRelease
            # 创建release
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ inputs.version }}
                  release_name: ${{ inputs.root_sol }} ${{ inputs.version }}
                  draft: false
                  prerelease: false
            # 上传至release的资源
            - name: Upload release binaries
              uses: alexellis/upload-assets@0.2.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  asset_paths: '["./build/app/outputs/apk/release/SmsF_*"]'
